spring:
  mail: 
    host: smtp.gmail.com
    port: 587
    username: mitimiti.app@gmail.com
    password: Mitimiti1234
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    enable: true
  datasource: 
    url: jdbc:mysql://localhost:3306/mitmitbd_persistida?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie

